package com.opspilot.event;

public enum EventType {
    RESOURCE_CREATED,
    RESOURCE_DELETED,
    RESOURCE_STARTED,
    RESOURCE_STOPPED,
    RESOURCE_FAILED,
    DEPLOYMENT_STARTED,
    DEPLOYMENT_FAILED,
    DEPLOYMENT_SUCCEEDED,
    POD_CRASHED,
    CONTAINER_EXITED,
    HEALTH_CHECK_FAILED,
    PIPELINE_FAILED,
    REPEATED_ERROR_LOGS,
    HIGH_CPU,
    HIGH_MEMORY,
    ALERT_TRIGGERED,
    ALERT_RESOLVED
}
