import React, { useEffect, useState } from 'react';
import { Activity, BellRing, Boxes, FileClock, GitBranch, Plus, RefreshCw, Save, ShieldCheck, Trash2, UsersRound, X } from 'lucide-react';
import { api, type AdminOverview, type AuditLog, type IntegrationSettings, type PlatformSetting } from '../services/api';
import { SidebarLayout } from '../components/SidebarLayout';
import { useConfirm } from '../components/ConfirmProvider';

export const AdminGovernance: React.FC = () => {
  const [overview, setOverview] = useState<AdminOverview | null>(null);
  const [auditLogs, setAuditLogs] = useState<AuditLog[]>([]);
  const [integrations, setIntegrations] = useState<IntegrationSettings[]>([]);
  const [settings, setSettings] = useState<PlatformSetting[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);
  const [newIntegration, setNewIntegration] = useState({ name: '', providerType: 'GITHUB', configJson: '', active: true });
  const { confirm } = useConfirm();

  const load = async () => {
    setLoading(true); setError('');
    try {
      const [summary, audit, connected, platformSettings] = await Promise.all([api.getAdminOverview(), api.getAuditLogs(), api.getAdminIntegrations(), api.getPlatformSettings()]);
      setOverview(summary); setAuditLogs(audit); setIntegrations(connected); setSettings(platformSettings);
    } catch (err: any) { setError(err.response?.data?.message || 'Unable to load governance data.'); } finally { setLoading(false); }
  };
  useEffect(() => { load(); }, []);
  const saveIntegration = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { await api.saveAdminIntegration(newIntegration); setNewIntegration({ name: '', providerType: 'GITHUB', configJson: '', active: true }); await load(); } catch (err: any) { setError(err.response?.data?.message || 'Unable to save integration.'); } finally { setSaving(false); } };
  const saveSetting = async (key: string, value: string) => { try { await api.savePlatformSetting(key, value); await load(); } catch (err: any) { setError(err.response?.data?.message || 'Unable to save platform setting.'); } };
  const removeIntegration = async (id: number) => { if (!await confirm('Remove this integration?', { isDestructive: true })) return; try { await api.deleteAdminIntegration(id); await load(); } catch (err: any) { setError(err.response?.data?.message || 'Unable to remove integration.'); } };


  const cards = overview ? [
    { label: 'Platform users', value: overview.userCount, detail: `${overview.activeUserCount} active accounts`, Icon: UsersRound, tone: 'text-op-accent bg-op-accent/10' },
    { label: 'Projects', value: overview.projectCount, detail: 'Across all workspaces', Icon: Boxes, tone: 'text-violet-600 bg-violet-50' },
    { label: 'Integrations', value: overview.integrationCount, detail: 'Platform connections', Icon: GitBranch, tone: 'text-sky-600 bg-sky-50' },
    { label: 'Audit events', value: overview.auditEventCount, detail: 'Recorded platform actions', Icon: FileClock, tone: 'text-emerald-600 bg-emerald-50' },
  ] : [];

  return <SidebarLayout><div className="mx-auto max-w-[1500px] space-y-6 p-5 md:p-8">
    <header className="flex flex-col gap-5 rounded-3xl border border-op-border bg-gradient-to-br from-white via-op-raised to-op-bg p-6 shadow-sm md:flex-row md:items-end md:justify-between">
      <div><div className="mb-3 flex items-center gap-2 text-[11px] font-black uppercase tracking-[0.2em] text-op-accent"><ShieldCheck className="h-4 w-4" /> Administrator workspace</div><h1 className="text-3xl font-black tracking-tight text-op-fg">Platform governance</h1><p className="mt-2 text-sm text-op-muted">Platform-wide activity, integrations, access controls, and notification settings.</p></div>
      <button onClick={load} className="inline-flex items-center justify-center gap-2 rounded-xl border border-op-border bg-white px-4 py-2.5 text-sm font-bold text-op-muted shadow-sm transition hover:border-op-accent/20 hover:text-op-accent"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Refresh</button>
    </header>
    {error && <div role="alert" className="flex items-center justify-between rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-medium text-rose-800"><span>{error}</span><button onClick={() => setError('')}><X className="h-4 w-4" /></button></div>}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ label, value, detail, Icon, tone }) => <div key={label} className="rounded-2xl border border-op-border bg-op-surface p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-op-muted">{label}</p><p className="mt-2 text-3xl font-black text-op-fg">{value}</p></div><span className={`grid h-10 w-10 place-items-center rounded-xl ${tone}`}><Icon className="h-5 w-5" /></span></div><p className="mt-3 text-xs font-medium text-op-muted">{detail}</p></div>)}</section>
    <div className="grid gap-6 xl:grid-cols-[1.1fr_0.9fr]">
      <section className="overflow-hidden rounded-3xl border border-op-border bg-op-surface shadow-sm"><div className="flex items-center justify-between border-b border-op-border px-5 py-4"><div><h2 className="font-black text-op-fg">Audit activity</h2><p className="mt-1 text-xs text-op-muted">Latest platform governance and project actions</p></div><FileClock className="h-5 w-5 text-op-accent" /></div><div className="max-h-[390px] divide-y divide-op-border overflow-y-auto">{loading ? <p className="p-6 text-sm text-op-muted">Loading activity…</p> : auditLogs.length === 0 ? <p className="p-6 text-sm text-op-muted">No audit activity recorded yet.</p> : auditLogs.map((entry) => <div key={entry.id} className="flex gap-3 px-5 py-4"><span className="mt-0.5 grid h-8 w-8 shrink-0 place-items-center rounded-xl bg-op-accent/10 text-op-accent"><Activity className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="text-sm font-bold text-op-fg">{entry.details || entry.action}</p><p className="mt-1 text-xs text-op-muted">{entry.actorName} · {entry.resourceType} · {new Date(entry.timestamp).toLocaleString()}</p></div></div>)}</div></section>
      <section className="rounded-3xl border border-op-border bg-op-surface p-5 shadow-sm"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-sky-50 text-sky-600"><GitBranch className="h-5 w-5" /></span><div><h2 className="font-black text-op-fg">Integrations</h2><p className="text-xs text-op-muted">Manage connected providers</p></div></div><div className="mt-4 space-y-2">{integrations.map((integration) => <div key={integration.id} className="flex items-center justify-between rounded-xl border border-op-border bg-op-raised px-3 py-2.5"><div><p className="text-sm font-bold text-op-fg">{integration.name}</p><p className="text-[11px] font-bold uppercase tracking-wider text-op-muted">{integration.providerType}</p></div><div className="flex items-center gap-1"><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${integration.active ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-200 text-slate-600'}`}>{integration.active ? 'Active' : 'Disabled'}</span><button onClick={() => integration.id && removeIntegration(integration.id)} title="Remove integration" className="rounded-lg p-1.5 text-op-muted hover:bg-rose-100 hover:text-rose-600"><Trash2 className="h-3.5 w-3.5" /></button></div></div>)}</div><form onSubmit={saveIntegration} className="mt-4 grid gap-2 border-t border-op-border pt-4"><input required value={newIntegration.name} onChange={(e) => setNewIntegration({ ...newIntegration, name: e.target.value })} placeholder="Integration name" className="rounded-xl border border-op-border px-3 py-2.5 text-sm outline-none focus:border-op-accent" /><textarea value={newIntegration.configJson} onChange={(e) => setNewIntegration({ ...newIntegration, configJson: e.target.value })} placeholder="Configuration JSON (optional)" className="min-h-16 rounded-xl border border-op-border px-3 py-2.5 font-mono text-xs outline-none focus:border-op-accent" /><div className="flex gap-2"><select value={newIntegration.providerType} onChange={(e) => setNewIntegration({ ...newIntegration, providerType: e.target.value })} className="rounded-xl border border-op-border px-3 py-2.5 text-sm font-bold text-op-fg"><option value="GITHUB">GitHub</option><option value="LOG_SOURCE">Log source</option><option value="SLACK">Slack</option></select><button disabled={saving} className="ml-auto inline-flex items-center gap-1 rounded-xl bg-op-accent px-3 py-2.5 text-xs font-bold text-op-accent-fg disabled:opacity-60"><Plus className="h-4 w-4" />Add</button></div></form></section>
    </div>
    <section className="rounded-3xl border border-op-border bg-op-surface p-5 shadow-sm"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-amber-50 text-amber-600"><BellRing className="h-5 w-5" /></span><div><h2 className="font-black text-op-fg">Platform notification settings</h2><p className="text-xs text-op-muted">Organization-wide alert preferences</p></div></div><div className="mt-4 grid gap-3 md:grid-cols-2">{settings.length === 0 ? <button onClick={() => saveSetting('alerts.enabled', 'true')} className="rounded-xl border border-dashed border-op-border px-4 py-4 text-left text-sm font-bold text-op-accent hover:border-op-accent/20 hover:bg-op-accent/10">Enable platform alerts</button> : settings.map((setting) => <div key={setting.id} className="flex items-center justify-between rounded-xl border border-op-border bg-op-raised px-4 py-3"><div><p className="text-sm font-bold text-op-fg">{setting.settingKey.replace(/[._]/g, ' ')}</p><p className="text-xs text-op-muted">Current value: {setting.settingValue}</p></div><button onClick={() => saveSetting(setting.settingKey, setting.settingValue === 'true' ? 'false' : 'true')} className="rounded-lg bg-op-surface p-2 text-op-accent shadow-sm border border-op-border"><Save className="h-4 w-4" /></button></div>)}</div></section>
  </div></SidebarLayout>;
};
