server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://127.0.0.1:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**, /api/v1/auth/**
        - id: observability-service
          uri: lb://observability-service
          predicates:
            - Path=/api/logs/**, /api/metrics/**, /api/notifications/**, /api/webhooks/**, /api/ai/**, /api/monitoring/**, /api/v1/logs/**, /api/v1/metrics/**, /api/v1/notifications/**, /api/v1/webhooks/**, /api/v1/ai/**, /api/v1/monitoring/**, /api/v1/log-sources/**, /api/v1/projects/*/log-sources, /api/v1/ingest/**, /api/commits/**, /api/v1/commits/**
        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/api/projects/**, /api/deployments/**, /api/docker/**, /api/kubernetes/**, /api/cicd/**, /api/users, /api/users/**, /api/admin/**, /api/v1/projects/**, /api/v1/deployments/**, /api/v1/docker/**, /api/v1/kubernetes/**, /api/v1/cicd/**, /api/v1/users, /api/v1/users/**, /api/v1/admin/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-registry:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
